# Generated by Django 4.2.16 on 2024-11-04 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siakap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='siakap.project'),
        ),
        migrations.CreateModel(
            name='Failcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failcodeID', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failcodes', to='siakap.station')),
            ],
        ),
    ]
